#!/usr/bin/env bash
#
# Regenerates database/apply_006_to_034.sql — one file to paste into the
# Supabase SQL editor to bring an older database up to the current schema.
#
# Why a bundle at all: migrations are applied to Supabase by hand, so the
# number of separate pastes is the number of chances to stop halfway, and a
# half-applied schema is worse than an old one.
#
# Every migration is re-runnable, so running this against a database that is
# already part-way through is safe and is the normal way to use it.
#
# Usage:  scripts/build-migration-bundle.sh [first] [last]
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

first="${1:-006}"
last="${2:-034}"
out="database/apply_${first}_to_${last}.sql"

files=()
for f in database/migrations/*.sql; do
    n="$(basename "$f" | cut -d_ -f1)"
    # Zero-padded three-digit numbers compare correctly as strings.
    if [[ "$n" > "$first" || "$n" == "$first" ]] && [[ "$n" < "$last" || "$n" == "$last" ]]; then
        files+=("$f")
    fi
done

if [ ${#files[@]} -eq 0 ]; then
    echo "No migrations between $first and $last." >&2
    exit 1
fi

{
    cat <<HEADER
-- ============================================================
-- $(basename "$out") — applies migrations $first through $last in order.
--
-- Paste this whole file into the Supabase SQL editor and run it once.
--
-- Safe to run on a database at any point in this range, and safe to run
-- twice: every migration drops what it recreates and creates nothing
-- unconditionally. Wrapped in a single transaction as well, so an
-- interruption leaves the schema where it started rather than half-way.
--
-- Generated by scripts/build-migration-bundle.sh. Regenerate rather than
-- editing this by hand.
-- ============================================================

begin;
HEADER

    for f in "${files[@]}"; do
        printf '\n\n-- ============================================================\n'
        printf -- '-- %s\n' "$(basename "$f")"
        printf -- '-- ============================================================\n'
        cat "$f"
    done

    cat <<'FOOTER'


commit;

-- ------------------------------------------------------------
-- PostgREST caches the list of functions it will expose. Without this it
-- can keep answering "Could not find the function ... in the schema cache"
-- for a minute or so after the functions exist.
-- ------------------------------------------------------------
notify pgrst, 'reload schema';
FOOTER
} > "$out"

echo "Wrote $out from ${#files[@]} migrations:"
printf '  %s\n' "${files[@]##*/}"
