#!/usr/bin/env bash
#
# Regenerates database/apply_006_to_010.sql — one file to paste into the
# Supabase SQL editor to bring a database that is at 005 up to 010.
#
# Why a bundle at all: migrations are applied to Supabase by hand, so the
# number of separate pastes is the number of chances to stop halfway. Several
# of these files are not re-runnable (006 fails on a policy that already
# exists), and a half-applied schema is worse than an old one.
#
# Usage:  scripts/build-migration-bundle.sh [first] [last]
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

first="${1:-006}"
last="${2:-010}"
out="database/apply_${first}_to_${last}.sql"

files=()
for f in database/migrations/*.sql; do
    n="$(basename "$f" | cut -d_ -f1)"
    # Zero-padded three-digit numbers compare correctly as strings.
    if [[ "$n" > "$first" || "$n" == "$first" ]] && [[ "$n" < "$last" || "$n" == "$last" ]]; then
        files+=("$f")
    fi
done

if [ ${#files[@]} -eq 0 ]; then
    echo "No migrations between $first and $last." >&2
    exit 1
fi

{
    cat <<HEADER
-- ============================================================
-- $(basename "$out") — applies migrations $first through $last in order.
--
-- Paste this whole file into the Supabase SQL editor and run it once.
--
-- Wrapped in a single transaction on purpose. Several of these migrations
-- are not re-runnable — 006 fails on a policy that already exists — and a
-- file that stops halfway through leaves the schema in a state that is
-- neither the old one nor the new one. This way it either all lands or
-- nothing does, and a second run fails harmlessly with everything intact.
--
-- Generated by scripts/build-migration-bundle.sh. Regenerate rather than
-- editing this by hand.
-- ============================================================

begin;
HEADER

    for f in "${files[@]}"; do
        printf '\n\n-- ============================================================\n'
        printf -- '-- %s\n' "$(basename "$f")"
        printf -- '-- ============================================================\n'
        cat "$f"
    done

    cat <<'FOOTER'


commit;

-- ------------------------------------------------------------
-- PostgREST caches the list of functions it will expose. Without this it
-- can keep answering "Could not find the function ... in the schema cache"
-- for a minute or so after the functions exist.
-- ------------------------------------------------------------
notify pgrst, 'reload schema';
FOOTER
} > "$out"

echo "Wrote $out from ${#files[@]} migrations:"
printf '  %s\n' "${files[@]##*/}"
